# Generated by Django 4.2 on 2025-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_faculty_options_alter_resume_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="graduation_year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
