# Generated by Django 4.2 on 2025-01-18 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_faculty_created_at_alter_resume_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 12, 20, 13, 199468, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 12, 20, 13, 199607, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 12, 20, 13, 199811, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.resume'),
        ),
    ]
