# Generated by Django 4.2 on 2025-01-18 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_avatar_alter_faculty_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 15, 19, 35, 945763, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 15, 19, 35, 945906, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 15, 19, 35, 946109, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.ManyToManyField(blank=True, to='students.resume'),
        ),
    ]
