# Generated by Django 4.2 on 2025-01-18 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_faculty_created_at_alter_resume_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 15, 58, 35, 999888, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 15, 58, 36, 128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 15, 58, 36, 618, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='students.skill'),
        ),
    ]
