# Generated by Django 4.2 on 2025-01-18 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_skill_alter_faculty_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 16, 48, 22, 907399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 16, 48, 22, 907581, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 16, 48, 22, 907829, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
