# Generated by Django 4.2 on 2025-01-18 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_certificate_resume_portfolio_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='certificates',
        ),
        migrations.AddField(
            model_name='certificate',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 17, 43, 25, 12715, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 17, 43, 25, 12859, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 17, 43, 25, 13259, tzinfo=datetime.timezone.utc)),
        ),
    ]
