# Generated by Django 4.2 on 2025-01-20 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_remove_resume_certificates_certificate_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 15, 10, 48, 873831, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 15, 10, 48, 873943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 15, 10, 48, 874271, tzinfo=datetime.timezone.utc)),
        ),
    ]
