version: '3.7'

services:
  redis:
    image: redis:alpine
    hostname: redis
    networks:
      - live
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    networks:
      - live
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A UniversityCareerCenter worker -l info"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - web
    restart: on-failure
    networks:
      - live
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A UniversityCareerCenter beat -l info"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - celery-worker
    restart: on-failure
    networks:
      - live
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    networks:
      - live

networks:
  live: