# Generated by Django 4.2 on 2024-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_application_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
