# Generated by Django 4.2 on 2025-01-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_application_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["status"],
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
