# Generated by Django 4.2 on 2025-01-13 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_alter_application_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 13, 15, 55, 58, 246599, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
