# Generated by Django 4.2 on 2025-01-13 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_alter_application_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 13, 16, 7, 49, 868650, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
