# Generated by Django 4.2.16 on 2024-11-18 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=150000, max_digits=10),
            preserve_default=False,
        ),
    ]
