# Generated by Django 4.2 on 2025-01-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0003_company_alter_vacancy_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["title"],
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
