# Generated by Django 4.2 on 2025-01-18 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_alter_company_created_at_alter_vacancy_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 12, 20, 13, 198923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 12, 20, 13, 199277, tzinfo=datetime.timezone.utc)),
        ),
    ]
